name: Platform packages sync from -develop/ to -stable/

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Stack to sync'
        type: choice
        options:
        - heroku-18
        - heroku-20
        - heroku-22
        required: true
      dry-run:
        description: 'Only list package changes, without syncing'
        type: boolean
        default: false
        required: false

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cached Docker image
        id: restore-docker
        uses: actions/cache/restore@v3
        with:
          key: docker-cache-heroku-php-build-${{inputs.stack}}.${{github.sha}}
          path: /tmp/docker-cache.tar.gz
      - name: Load cached Docker image
        if: steps.restore-docker.outputs.cache-hit == 'true'
        run: docker load -i /tmp/docker-cache.tar.gz
      - name: Build Docker image
        if: steps.restore-docker.outputs.cache-hit != 'true'
        run: docker build --tag heroku-php-build-${{inputs.stack}}:${{github.sha}} --file support/build/_docker/${{inputs.stack}}.Dockerfile .
      - name: Save built Docker image
        if: steps.restore-docker.outputs.cache-hit != 'true'
        run: docker save heroku-php-build-${{inputs.stack}}:${{github.sha}} | gzip -1 > /tmp/docker-cache.tar.gz
      - name: Cache built Docker image
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.restore-docker.outputs.cache-primary-key }}
          path: /tmp/docker-cache.tar.gz
      - name: Dry-run sync.sh to show package changes available for syncing to production bucket
        if: ${{ inputs.dry-run == true }}
        run: yes n 2>/dev/null | docker run --rm -i --env-file=support/build/_docker/env.default heroku-php-build-${{inputs.stack}}:${{github.sha}} sync.sh lang-php dist-${{inputs.stack}}-stable/
      - name: Sync changed packages to production bucket
        if: ${{ inputs.dry-run == false }}
        run: yes 2>/dev/null | docker run --rm -i --env-file=support/build/_docker/env.default heroku-php-build-${{inputs.stack}}:${{github.sha}} sync.sh lang-php dist-${{inputs.stack}}-stable/
